import React, { useState } from "react";
import { CheckCircle2, CircleDashed, Clock3, Plus, Users } from "lucide-react";
import { json, jsonOptions } from "../api.js";
import { ErrorState, Loading, Tabs } from "../components/Ui.jsx";
import { useAsyncJson } from "../hooks.js";
import { DEFAULT_MEMBER, TEAM } from "../team.js";

export function CollabPage() {
  const {data,loading,error,reload}=useAsyncJson("/api/collab");
  const [view,setView]=useState("tasks");const [adding,setAdding]=useState(false);const [text,setText]=useState("");
  if(loading)return <Loading label="加载协同 Hub…"/>;if(error)return <ErrorState message={error} onRetry={reload}/>;
  async function patchTask(id,status){await json(`/api/collab/tasks/${id}`,jsonOptions("PATCH",{status}));await reload();}
  async function addUpdate(event){event.preventDefault();await json("/api/collab/updates",jsonOptions("POST",{memberId:DEFAULT_MEMBER.id,memberName:DEFAULT_MEMBER.name,groupId:TEAM.id,message:text,status:"active"}));setText("");setAdding(false);await reload();}
  return <div className="collab-page page-pad"><header className="page-heading"><div><Users size={20}/><span><small>协同 Hub</small><h1>任务与小组动态</h1></span></div><button className="primary-button" onClick={()=>setAdding(true)}><Plus size={14}/>发布动态</button></header><section className="collab-summary"><span><strong>{data.members?.length||5}</strong>队员</span><span><strong>{data.tasks?.filter(item=>item.status==="done").length||0}/{data.tasks?.length||0}</strong>任务完成</span><span><strong>{data.updates?.length||0}</strong>组内动态</span></section><Tabs value={view} onChange={setView} items={[{value:"tasks",label:"协作任务"},{value:"updates",label:"小组动态"},{value:"members",label:"成员"}]}/>{adding?<form className="update-form" onSubmit={addUpdate}><textarea required value={text} onChange={event=>setText(event.target.value)} placeholder="同步今天完成的调研、证据缺口或下一步安排…"/><div><button type="button" onClick={()=>setAdding(false)}>取消</button><button className="primary-button">发布动态</button></div></form>:null}{view==="tasks"?<section className="task-list">{(data.tasks||[]).map(task=><article key={task.id}><button className={`task-check ${task.status}`} title="切换任务状态" onClick={()=>void patchTask(task.id,task.status==="done"?"todo":"done")}>{task.status==="done"?<CheckCircle2/>:task.status==="active"?<Clock3/>:<CircleDashed/>}</button><div><h2>{task.title}</h2><p>{task.description||task.body||"按调研路线推进并同步证据。"}</p><small>{task.assigneeName||task.memberName||TEAM.shortName} · {task.status||"todo"}</small></div></article>)}</section>:view==="updates"?<section className="update-list">{(data.updates||[]).map(item=><article key={item.id}><span>{(item.memberName||"组").slice(0,1)}</span><div><strong>{item.memberName||TEAM.shortName}</strong><p>{item.message||item.content||item.title}</p><time>{new Date(item.createdAt).toLocaleString("zh-CN")}</time></div></article>)}</section>:<section className="member-grid">{(data.members||[]).map(member=><article key={member.id||member.memberId}><span>{(member.name||member.memberName||"组").slice(0,1)}</span><strong>{member.name||member.memberName}</strong><small>{member.role||"调研员"}</small></article>)}</section>}</div>;
}
