import React, { useEffect, useMemo, useState } from "react";
import { Archive, CheckCircle2, CircleDashed, ExternalLink, Link2, ListChecks, RefreshCw, ShieldAlert, Users } from "lucide-react";
import { json, jsonOptions } from "../api.js";
import { AppLink } from "../components/Shell.jsx";
import { ErrorState, Loading, Progress, StatusDot, Tabs } from "../components/Ui.jsx";
import { DEFAULT_MEMBER, TEAM } from "../team.js";

export function CollabHubPage(){
  const [state,setState]=useState({loading:true,error:""});const [statusFilter,setStatusFilter]=useState("active");const [memberId,setMemberId]=useState(DEFAULT_MEMBER.id);const [companyId,setCompanyId]=useState("");
  const load=async()=>{setState(current=>({...current,loading:true,error:""}));try{const [collab,dashboard,problems,solutions,media,teamConfig]=await Promise.all([json("/api/collab"),json("/api/research-dashboard"),json(`/api/problems?groupId=${TEAM.id}`),json(`/api/solutions?groupId=${TEAM.id}`),json(`/api/media?groupId=${TEAM.id}`),json("/api/team-config")]);setState({loading:false,error:"",collab,dashboard,teamConfig,problems:problems.problems??[],solutions:solutions.solutions??[],media:media.items??[]});const first=dashboard.members?.[0]?.sites?.[0];setCompanyId(current=>current||first?.companyId||"");}catch(error){setState({loading:false,error:error.message});}};
  useEffect(()=>{void load();},[]);
  const member=state.dashboard?.members?.find(item=>item.memberId===memberId)??state.dashboard?.members?.[0];const sites=member?.sites??[];const site=sites.find(item=>item.companyId===companyId)??sites[0];
  const siteProblems=useMemo(()=>state.problems?.filter(item=>item.memberId===member?.memberId&&item.companyId===site?.companyId)??[],[state.problems,member?.memberId,site?.companyId]);
  const linkedSolutions=useMemo(()=>state.solutions?.filter(item=>item.memberId===member?.memberId&&item.companyId===site?.companyId)??[],[state.solutions,member?.memberId,site?.companyId]);
  const routeCards=(state.teamConfig?.routes??[]).map(route=>({id:route.id,title:`Day ${route.day} · ${route.label}`,subtitle:`${route.memberIds.map(id=>state.teamConfig.members.find(member=>member.id===id)?.name).join("、")} · ${route.stops.map(stop=>stop.companyName).join("、")}`}));
  if(state.loading)return <Loading label="加载小组协同 Hub…"/>;if(state.error)return <ErrorState message={state.error} onRetry={load}/>;
  async function patchTask(id,status){await json(`/api/collab/tasks/${id}`,jsonOptions("PATCH",{status}));await load();}
  return <div className="collab-hub page-pad"><header className="collab-hero"><div><Users size={22}/><span><small>2026 RBCC · {TEAM.theme}</small><h1>小组协同 Hub</h1><p>问题库、证据链、全组进度与过程留痕集中呈现</p></span></div><div><AppLink href="/screen">协作大屏 <ExternalLink size={12}/></AppLink><AppLink href="/screen/roadshow">全功能路演 <ExternalLink size={12}/></AppLink><AppLink href="/screen/roadshow?preset=cinema">精简路演 <ExternalLink size={12}/></AppLink><AppLink href="/dashboard">调研报告 <ExternalLink size={12}/></AppLink><button onClick={()=>void load()}><RefreshCw size={13}/>立即刷新</button></div></header>
    <section className="collab-kpis"><span><small>全组综合</small><strong>{state.dashboard.summary?.siteAssignmentCount?Math.round((state.dashboard.summary.sitesQuestionsComplete||0)/state.dashboard.summary.siteAssignmentCount*100):0}%</strong><Progress value={state.dashboard.summary?.siteAssignmentCount?Math.round((state.dashboard.summary.sitesQuestionsComplete||0)/state.dashboard.summary.siteAssignmentCount*100):0}/></span><span><small>问题完成</small><strong>{state.dashboard.summary?.sitesQuestionsComplete||0}/{state.dashboard.summary?.siteAssignmentCount||0}</strong></span><span><small>验证双线</small><strong>{state.dashboard.summary?.sitesDualValidated||0}/{state.dashboard.summary?.siteAssignmentCount||0}</strong></span><span><small>现场留痕</small><strong>{state.media.length}</strong></span><span><small>田野问题库</small><strong>{state.problems.length}</strong></span><span><small>分析方案</small><strong>{state.solutions.length}</strong></span></section>
    <section className="collab-columns"><article className="site-validation"><header><ListChecks size={16}/><div><h2>我的站点 · 预设问题与验证</h2><p>选择队员和站点，检查调研前假设是否被现场证据验证</p></div></header><div className="site-selectors"><select value={member.memberId} onChange={event=>{setMemberId(event.target.value);const next=state.dashboard.members.find(item=>item.memberId===event.target.value);setCompanyId(next?.sites?.[0]?.companyId||"");}}>{state.dashboard.members.map(item=><option key={item.memberId} value={item.memberId}>{item.memberName}</option>)}</select><select value={site?.companyId||""} onChange={event=>setCompanyId(event.target.value)}>{sites.map(item=><option key={item.companyId} value={item.companyId}>{item.companyName}</option>)}</select></div><div className="question-list">{(site?.questions??[]).slice(0,10).map((question,index)=>{const outcome=question.validationOutcome;const label=outcome==="confirmed"?"成立":outcome==="partial"?"部分成立":outcome==="refuted"?"证伪":"待验证";return <div key={question.id||index}><span>{index+1}</span><p>{question.text}<small>{question.evidenceSource||question.answer||"尚未记录证据"}</small></p><StatusDot ok={outcome==="confirmed"} label={label}/></div>})}</div></article>
      <article className="evidence-chain"><section><header><ShieldAlert size={16}/><div><h2>① 田野问题库</h2><p>{site?.companyName} · {siteProblems.length} 条</p></div></header>{siteProblems.slice(0,7).map(item=><div className="problem-item" key={item.id}><strong>{item.title||item.problemStatement}</strong><p>{item.evidence||item.observation}</p><small>{item.validationOutcome||"pending"} · 逐题 {item.questionIds?.length||0} · 留痕 {item.observationIds?.length||0}</small></div>)}</section><section><header><Link2 size={16}/><div><h2>② 方案 · 问题证据链</h2><p>方案必须引用已验证问题记录</p></div></header>{linkedSolutions.slice(0,5).map(item=><div className="solution-item" key={item.id}><strong>{item.title}</strong><p>{item.description}</p><small>挂钩 {item.linkedProblemIds?.length||0} 条问题 · {item.validationStatus||"draft"}</small></div>)}</section></article></section>
    <section className="group-progress"><header><div><h2>分线路进度</h2><p>按三日官方路线查看外勤覆盖、任务和受阻项</p></div><AppLink href="/dashboard">小组看板 →</AppLink></header><div>{routeCards.map((group,index)=><button key={group.id}><span className="group-index">{index+1}</span><div><strong>{group.title}</strong><p>{group.subtitle}</p><small>路线资产持续同步</small></div><Progress value={state.dashboard.summary?.siteAssignmentCount?Math.round((state.dashboard.summary.sitesQuestionsComplete||0)/state.dashboard.summary.siteAssignmentCount*100):0} tone="cyan"/></button>)}</div></section>
    <section className="collab-bottom"><article><header><Archive size={16}/><div><h2>{TEAM.name} · 过程留痕库</h2><p>最新图片、录音和文字证据</p></div><AppLink href="/traces">打开留痕库</AppLink></header><div className="mini-traces">{state.media.slice(0,8).map(item=><span key={item.id}><strong>{item.memberName} · {item.companyName}</strong><small>{item.textContent||item.caption||item.title}</small></span>)}</div></article><article><header><h2>全组动态流</h2></header><div className="mini-feed">{(state.collab.updates??[]).map(item=><span key={item.id}><strong>{item.memberName||TEAM.shortName}</strong><p>{item.message||item.content||item.title}</p></span>)}</div></article></section>
    <section className="all-tasks"><header><div><h2>全部任务看板</h2><p>统一查看进行中、受阻和已完成任务</p></div><Tabs value={statusFilter} onChange={setStatusFilter} items={[{value:"active",label:"进行中"},{value:"blocked",label:"受阻"},{value:"done",label:"已完成"},{value:"all",label:"全部"}]}/></header><div>{(state.collab.tasks??[]).filter(item=>statusFilter==="all"||item.status===statusFilter||(statusFilter==="active"&&item.status==="todo")).map(task=><article key={task.id}><button title="切换完成状态" onClick={()=>void patchTask(task.id,task.status==="done"?"active":"done")}>{task.status==="done"?<CheckCircle2/>:<CircleDashed/>}</button><div><strong>{task.title}</strong><p>{task.description||task.body||"按调研路线推进并同步证据"}</p><small>{task.assigneeName||task.memberName||TEAM.shortName} · {task.status}</small></div></article>)}</div></section>
  </div>;
}
